__version__ = "1.0.1"
__git_commiter_name__ = "Itai Shirav"
__git_commiter_email__ = "itais@infinidat.com"
__git_branch__ = u'(HEAD detached at v1.0.1)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = 'f4da4d480e7893cdee43805d10015b0d4d9b12cf'
__git_head_subject__ = u'Finished Release v1.0'
__git_head_message__ = u''
__git_dirty_diff__ = u''
__git_commit_date__ = '2017-12-29 18:30:49'
